version: 1
accounts:
  - name: creator
    coins: ["1000token", "100000000stake"]
  - name: transporter
    coins: ["500token"]
  - name: customer
    coins: ["500token"]
validator:
  name: creator
  staked: "100000000stake"